name: 'GHCR Tag and Push'
description: 'Tag and Push to Github Container Registry'
inputs:
  tag:
    description: 'tag to give to latest image'
    required: true
  image_name:
    description: 'name of the docker image to work with'
    required: true
runs:
  using: "composite"
  steps:
      - name: Store latest docker image on GHCR
        run: |
             TAG=ghcr.io/${{ github.repository_owner }}/${{ inputs.image_name }}:${{ inputs.tag }}
             docker tag ${{ inputs.image_name }}:latest $TAG
             docker push $TAG
        shell: bash
        continue-on-error: true
